FORMAT: 1A
HOST: https://still-plains-85177.herokuapp.com

# E-Commerce Server

E-Commerce Server is an API for Admin to CRUD products and Customers to add product to their own cart then checkout.

# Group Admin

## Login [/admin/login]
### Login [POST]

+ Request (application/json)

        {
            "email": "mail@mail.com",
            "password": "thisispassword"
        }

+ Response 200 (application/json)

        {
            "token": <generated token>
        }
        
+ Response 400 (application/json)

        {
            "message": "Bad Request",
            "errors": [
                "Wrong email/password"
            ]
        }
    
+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        }
        
        
## Show Users [/admin/users]
### Users [GET]

+ Request
    + Headers
    
            token: <generated token>

+ Response 200 (application/json)

        {
            "data": [
                {
                    "id": 1,
                    "email": "admin@admin.com",
                    "role": "admin"
                }
            ]
        }


+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        }
        
        
# Group Users
## Register [/users/register]
### Register [POST]
+ Request (application/json)

        {
            "email": "mail@mail.com",
            "password": "thisispassword"
        }

+ Response 201 (application/json)

        {
            "token": <generated token>
        }
        
+ Response 400 (application/json)

        {
            "message": "Bad Request",
            "errors": [
                <validation errors>
            ]
        }
    
+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        }
        
## Login [/users/login]
### Login [POST]

+ Request (application/json)

        {
            "email": "mail@mail.com",
            "password": "thisispassword"
        }

+ Response 200 (application/json)

        {
            "token": <generated token>
        }
        
+ Response 400 (application/json)

        {
            "message": "Bad Request",
            "errors": [
                "Wrong email/password"
            ]
        }
    
+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        }
        


# Group Products
## Create and Read [/products]
### Create [POST]

+ Request (application/json)
    + Headers
        
            token: <generated token>
            
    + Body
    
            {
                "name" : "this is name of the product",
                "image_url" :"this is URL",
                "price" : 10000000,
                "stock" : 10
            }

+ Response 201 (application/json)

            {
                "id" : 1
                "name" : "this is name of the product",
                "image_url" :"this is URL",
                "price" : 10000000,
                "stock" : 10,
                "createdAt" : <date>,
                "updatedAt" : <date>
            }
            
+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : [<validation errors>]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
            
### Read [GET]

+ Request
    + Headers
    
            token: <generated token>

+ Response 200 (application/json)

            {
                "data": [
                    {
                        "id": 6,
                        "name": "Belt",
                        "image_url": "https://images.pexels.com/photos/89783/belts-belt-buckle-leather-metal-89783.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                        "price": 20000,
                        "stock": 12,
                        "createdAt": "2020-03-18T09:54:57.008Z",
                        "updatedAt": "2020-03-18T09:54:57.008Z"
                    },
                    {
                        "id": 7,
                        "name": "Hat",
                        "image_url": "https://images.pexels.com/photos/984619/pexels-photo-984619.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260",
                        "price": 15000,
                        "stock": 20,
                        "createdAt": "2020-03-18T09:57:16.976Z",
                        "updatedAt": "2020-03-18T09:57:16.976Z"
                    }
                ]
            }


+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        }
            
## Update and Delete Product [/products/{id}]

### Update [PUT]

+ Parameters 
    + id (number) - ID of the Product in the form of an integer


+ Request (application/json)
    + Headers
        
            token: <generated token>
            
    + Body
    
            {
                "name" : "this is name of the product updated"
                "image_url" :"this is URL",
                "price" : 10000000,
                "stock" : 10
            }

+ Response 200 (application/json)

            {
                "id" : 1
                "name" : "this is name of the product updated",
                "image_url" :"this is URL",
                "price" : 10000000,
                "stock" : 10,
                "createdAt" : <date>,
                "updatedAt" : <date>
            }
            
+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : [<validation errors>]
            }
            
            or
            
            {
                "message" : "Bad Request",
                "errors" : ["Product not found"]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
            
### Delete [DELETE]


+ Parameters 
    + id (number) - ID of the Product in the form of an integer


+ Request (application/json)
    + Headers
        
            token: <generated token>
            
+ Response 200 (application/json)

        {
            "data" : "deleted"
        }

+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : ["Product not found"]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
# Group Carts
## Add Product and Read Cart [/carts]
### Add Product to Cart [POST]

+ Request (application/json)
    + Headers
        
            token: <generated token>
            
    + Body
    
            {
                "ProductId" : 1
            }

+ Response 200 (application/json)

            {
                "message" : "Cart successfully updated"
            }
            
+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : ["You reached stock limit"]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
### Read Cart [GET]

+ Request
    + Headers
    
            token: <generated token>

+ Response 200 (application/json)

            {
                "data": [
                    {
                        "id": 40,
                        "UserId": 2,
                        "ProductId": 4,
                        "quantity": 1,
                        "totalPrice": 1000000,
                        "isPaid": true,
                        "createdAt": "2020-03-26T08:02:25.036Z",
                        "updatedAt": "2020-03-26T08:02:38.982Z",
                        "Product": {
                            "id": 4,
                            "name": "Samsung",
                            "image_url": "https://images.pexels.com/photos/214487/pexels-photo-214487.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            "price": 1000000,
                            "stock": 5,
                            "category": "electronic",
                            "createdAt": "2020-03-24T16:16:13.962Z",
                            "updatedAt": "2020-03-26T08:03:14.837Z"
                        }
                    },
                    {
                        "id": 41,
                        "UserId": 2,
                        "ProductId": 2,
                        "quantity": 1,
                        "totalPrice": 100000,
                        "isPaid": true,
                        "createdAt": "2020-03-26T08:02:27.357Z",
                        "updatedAt": "2020-03-26T08:02:38.983Z",
                        "Product": {
                            "id": 2,
                            "name": "T-shirt",
                            "image_url": "https://images.pexels.com/photos/1484808/pexels-photo-1484808.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            "price": 100000,
                            "stock": 3,
                            "category": "fashion",
                            "createdAt": "2020-03-24T16:13:06.907Z",
                            "updatedAt": "2020-03-26T08:03:14.838Z"
                        }
                    },
                ]
            }


+ Response 500 (application/json)

        {
            "message": "Internal Server Error"
        } 

## Update and Delete Cart [/carts/{id}]

### Update [PUT]

+ Parameters 
    + id (number) - ID of the Product in the form of an integer


+ Request (application/json)
    + Headers
        
            token: <generated token>

+ Response 200 (application/json)

            {
                "message" : "Cart successfully updated"
            }
            
+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : ["Cart not found"]
            }
            
            or
            
            {
                "message" : "Bad Request",
                "errors" : ["Product not found"]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
            
### Delete [DELETE]


+ Parameters 
    + id (number) - ID of the Product in the form of an integer


+ Request (application/json)
    + Headers
        
            token: <generated token>
            
+ Response 200 (application/json)

        {
            "message" : "Cart successfully deleted"
        }

+ Response 400 (application/json)

            {
                "message" : "Bad Request",
                "errors" : ["Cart not found"]
            }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }
            
## Checkout Cart [/carts/checkout]
### Checkout [GET]

+ Request (application/json)
    + Headers
        
            token: <generated token>
            
+ Response 200 (application/json)

        {
            "message" : "Checkout Success"
        }
            
+ Response 500 (application/json)

            {
                "message" : "Internal Server Error"
            }