const routers = require('express').Router()
const UserController = require('../controllers/userController')
const Productcontroller = require('../controllers/productController')
const {authorization} = require('../middlewares/authorization')
const {authentication} = require('../middlewares/authentication')
routers.post('/register',UserController.register)
routers.post('/login',UserController.login)
routers.post('/loginAdmin',UserController.loginAdmin)

routers.post('/product',authentication,authorization,Productcontroller.addProduct)
routers.get('/product',authentication,authorization,Productcontroller.getProduct)
routers.get('/product/:id',authentication,authorization,Productcontroller.getProductById)
routers.put('/product/:id',authentication,authorization,Productcontroller.updateProduct)
routers.delete('/product/:id',authentication,authorization,Productcontroller.deleteProduct)
module.exports = routers